version: '3.8'

services:
  nodisbot:
    image: nodisbot:local
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    restart: always
